### ISSUE TITLE
Submit to the NML list?

### ISSUE THREAD

**Issue by Zetaphor** [RileyGuy/Nodentify#1]
I was looking for a mod that did exactly this in the [Neos Modding Group list](https://www.neosmodloader.com/mods) and found that this mod is unfortunately missing. Thankfully someone linked me to it on Discord. Would you consider [submitting this mod to the list](https://www.neosmodloader.com/submission-tutorial.html) for greater discoverability?

**Comment by XDelta** [comment]
> I was looking for a mod that did exactly this in the [Neos Modding Group list](https://www.neosmodloader.com/mods) and found that this mod is unfortunately missing. Thankfully someone linked me to it on Discord. Would you consider [submitting this mod to the list](https://www.neosmodloader.com/submission-tutorial.html) for greater discoverability?

Was added Aug 28th
https://github.com/neos-modding-group/neos-mod-manifest/pull/110
