### ISSUE TITLE
Latest version of the code with the toggle node renaming config option hasn't been released yet.

### ISSUE THREAD

**Issue by Nytra** [RileyGuy/Nodentify#4]
Is there a reason why? It would be nice to not have to compile the mod myself to get this option.

**Comment by BlueCyro** [comment]
Updated the code a bit as per commit [d560bb0](https://github.com/RileyGuy/Nodentify/commit/d560bb040d3a5c70478e9364019f5dee0346f75d) and a release has been built as per version [1.0.5](https://github.com/RileyGuy/Nodentify/releases/tag/1.0.5).
Guess I just forgot to build Stiefel's pull request, woops!

**Comment by Nytra** [comment]
Thank you!
